NL = _{ ("\n" | "\r\n") }
WS = _{ (" " | "\t")* }
alpha = _{ 'a'..'z' | 'A'..'Z' }
digit = _{ '0'..'9' }
hex = _{ '0'..'9' | 'A'..'F' | 'a'..'f' }

Number = {
    (hex)+ ~ "h"
    | ('0'..'1')+ ~ "b" 
    | ('0'..'9')+
}
Ident   = { alpha ~ (alpha | digit | "_")* }

StringChar = _{ ! "\"" ~ ANY }
String  = {
    "\"" ~ StringChar+ ~ "\""
}

Parameter = _{ (Ident | Number | String) }
Argument = _{ Parameter ~ ("," ~ WS ~ Argument)? }

Label       = { WS    ~ Ident ~ ":" ~ (Comment | NL) }
Instruction = { Ident ~ WS    ~ (Argument | Comment | NL) } 
Comment     = { ";"   ~ ANY*  ~ NL }

Line = { WS ~ (Comment | Label | Instruction | NL) }
File = { SOI ~ (Line)* ~ EOI }